-- Gesture Synth "Community" service — Postgres schema.
-- Apply with:  psql "$DATABASE_URL" -f sql/schema.sql
--
-- All IDs are 10-character URL-safe random strings generated by the service.
-- Timestamps are timestamptz and are written by the service.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id            TEXT        PRIMARY KEY,
  handle        TEXT        NOT NULL,
  display_name  TEXT        NOT NULL,
  password_hash TEXT        NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_handle_key    UNIQUE (handle),
  CONSTRAINT users_handle_format CHECK (handle ~ '^[a-z0-9_]{3,24}$')
);

-- Bearer tokens are never stored in plain text; only their SHA-256 digest.
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT        PRIMARY KEY,
  user_id    TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);

CREATE TABLE IF NOT EXISTS items (
  id            TEXT        PRIMARY KEY,
  kind          TEXT        NOT NULL,
  title         TEXT        NOT NULL,
  description   TEXT        NOT NULL DEFAULT '',
  author_id     TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tags          TEXT[]      NOT NULL DEFAULT '{}',
  -- Opaque document owned by the client (song/preset/theme data). Max 2 MB,
  -- enforced by the service and by the check below.
  payload       JSONB       NOT NULL,
  -- Remix chain: the item this one was built from.
  parent_id     TEXT        REFERENCES items(id) ON DELETE SET NULL,
  like_count    INTEGER     NOT NULL DEFAULT 0,
  comment_count INTEGER     NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT items_kind_check
    CHECK (kind IN ('song', 'tutorial', 'preset', 'theme', 'loop')),
  CONSTRAINT items_payload_size_check
    CHECK (pg_column_size(payload) <= 2 * 1024 * 1024)
);
CREATE INDEX IF NOT EXISTS items_kind_idx       ON items (kind);
CREATE INDEX IF NOT EXISTS items_author_id_idx  ON items (author_id);
CREATE INDEX IF NOT EXISTS items_parent_id_idx  ON items (parent_id);
CREATE INDEX IF NOT EXISTS items_created_at_idx ON items (created_at DESC);
CREATE INDEX IF NOT EXISTS items_like_count_idx ON items (like_count DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS items_tags_idx       ON items USING GIN (tags);
-- Optional: speeds up the ILIKE search used by GET /items?q=
--   CREATE EXTENSION IF NOT EXISTS pg_trgm;
--   CREATE INDEX items_title_trgm_idx ON items USING GIN (title gin_trgm_ops);
--   CREATE INDEX items_description_trgm_idx ON items USING GIN (description gin_trgm_ops);

CREATE TABLE IF NOT EXISTS likes (
  user_id    TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_id    TEXT        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, item_id)
);
CREATE INDEX IF NOT EXISTS likes_item_id_idx ON likes (item_id);

CREATE TABLE IF NOT EXISTS comments (
  id         TEXT        PRIMARY KEY,
  item_id    TEXT        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  author_id  TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body       TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT comments_body_length_check
    CHECK (char_length(body) BETWEEN 1 AND 2000)
);
CREATE INDEX IF NOT EXISTS comments_item_id_created_at_idx
  ON comments (item_id, created_at);

-- One share code per item; /s/:code redirects to the frontend item page.
CREATE TABLE IF NOT EXISTS short_links (
  code       TEXT        PRIMARY KEY,
  item_id    TEXT        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT short_links_item_id_key UNIQUE (item_id),
  CONSTRAINT short_links_code_length CHECK (char_length(code) = 6)
);

COMMIT;
